In [39]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, Imputer, LabelEncoder
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

In [40]:
df = pd.read_csv("D:\\Lending Club\\Default.csv", low_memory=False)
df = df.dropna(axis=0)
df.head(5)

,addr_state,annual_inc,application_type,dti,earliest_cr_line,emp_length,emp_title,fico_range_high,fico_range_low,grade,...,pub_rec_bankruptcies,purpose,revol_bal,revol_util,sub_grade,term,title,total_acc,verification_status,zip_code
0,PA,55000.0,Individual,5.91,Aug-2003,10+ years,leadman,679.0,675.0,C,...,0.0,debt_consolidation,2765.0,29.7,C4,36 months,Debt consolidation,13.0,Not Verified,190xx
1,SD,65000.0,Individual,16.06,Dec-1999,10+ years,Engineer,719.0,715.0,C,...,0.0,small_business,21470.0,19.2,C1,36 months,Business,38.0,Not Verified,577xx
3,NJ,110000.0,Individual,17.06,Sep-2008,10+ years,Information Systems Officer,789.0,785.0,C,...,0.0,debt_consolidation,7802.0,11.6,C5,60 months,Debt consolidation,17.0,Source Verified,076xx
4,PA,104433.0,Individual,25.37,Jun-1998,3 years,Contract Specialist,699.0,695.0,F,...,0.0,major_purchase,21929.0,64.5,F1,60 months,Major purchase,35.0,Source Verified,174xx
5,GA,34000.0,Individual,10.20,Oct-1987,4 years,Veterinary Tecnician,694.0,690.0,C,...,0.0,debt_consolidation,8822.0,68.4,C3,36 months,Debt consolidation,6.0,Source Verified,300xx

In [41]:
col = df.loc[: , "fico_range_low": "fico_range_high"]
df["Score"] = col.mean(axis=1)

In [42]:
dropList = ["earliest_cr_line", "zip_code", "title", "id", "emp_title", "sub_grade", "issue_d", "fico_range_low", "fico_range_high"]
for i in dropList:
    df = df.drop([i], axis = 1)

In [43]:
list(df.columns.values)

['addr_state',
 'annual_inc',
 'application_type',
 'dti',
 'emp_length',
 'grade',
 'home_ownership',
 'initial_list_status',
 'installment',
 'int_rate',
 'loan_amnt',
 'loan_status',
 'mort_acc',
 'open_acc',
 'pub_rec',
 'pub_rec_bankruptcies',
 'purpose',
 'revol_bal',
 'revol_util',
 'term',
 'total_acc',
 'verification_status',
 'Score']

In [45]:
def to_int(x):
    if x[2] == "+":
        return 10
    elif x[0] == "<":
        return 0
    else:
        return int(x[0])
    
def loan(x):
    if x == "Fully Paid":
        return 0
    elif x == "Charged Off" or x == "Late (31-120 days)" or x == "Late (16-30 days)" or x == "Default":
        return 1
    elif x == "In Grace Period" or x == "Current":
        return 2
    
df["emp_length"] = df["emp_length"].apply(lambda x: to_int(x))
df["loan_status"] = df["loan_status"].apply(lambda x: loan(x))

In [48]:
list(df.columns.values)

['addr_state',
 'annual_inc',
 'application_type',
 'dti',
 'emp_length',
 'grade',
 'home_ownership',
 'initial_list_status',
 'installment',
 'int_rate',
 'loan_amnt',
 'loan_status',
 'mort_acc',
 'open_acc',
 'pub_rec',
 'pub_rec_bankruptcies',
 'purpose',
 'revol_bal',
 'revol_util',
 'term',
 'total_acc',
 'verification_status',
 'Score']

In [62]:
df['loan_status'].value_counts()

Fully Paid            964054
Current               794192
Charged Off           235550
Late (31-120 days)     19175
In Grace Period         7655
Late (16-30 days)       3792
Default                   34
Name: loan_status, dtype: int64